server:
  port: ${BUGTRACKER_SERVICE_PORT:8010}
  servlet:
    context-path: /api

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        jdbc:
          lob:
            non_contextual_creation: true
  liquibase:
    change-log: classpath:/db/master.xml
  datasource:
    username: ${BUGTRACKER_DB_USERNAME:postgres}
    password: ${BUGTRACKER_DB_PASSWORD:admin}
    url: ${BUGTRACKER_DB_URL:jdbc:postgresql://127.0.0.1:5432/bugtrackerdb}

# Security
jwt:
  secret: javaJWt
  expirationHours: 24