server:
  port: ${BUGTRACKER_SERVICE_PORT}
  servlet:
    context-path: /api

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        jdbc:
          lob:
            non_contextual_creation: true
  liquibase:
    change-log: classpath:/db/master.xml
  datasource:
    username: ${BUGTRACKER_DB_USERNAME}
    password: ${BUGTRACKER_DB_PASSWORD}
    url: ${BUGTRACKER_DB_URL}
  sql:
    init:
      mode: always
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
# Security
jwt:
  secret: javaJWt
  expirationHours: 24